package com.lanou.mapper.user;

import com.lanou.model.user.FinanceAccount;

import java.util.Map;

public interface FinanceAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Aug 13 16:53:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Aug 13 16:53:05 CST 2018
     */
    int insert(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Aug 13 16:53:05 CST 2018
     */
    int insertSelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Aug 13 16:53:05 CST 2018
     */
    FinanceAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Aug 13 16:53:05 CST 2018
     */
    int updateByPrimaryKeySelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Aug 13 16:53:05 CST 2018
     */
    int updateByPrimaryKey(FinanceAccount record);

    FinanceAccount selectByUid(Integer id);

    int updateFinanceAccountByUid(Map<String, Object> paramMap);

    /**
     * 收益返还：更新账户可用余额
     * @param paramMap
     * @return
     */
    int updateFinaceAccountByIncomeBack(Map<String, Object> paramMap);
}