package com.lanou.mapper.loan;

import com.lanou.model.loan.IncomeRecord;

import java.util.List;
import java.util.Map;

public interface IncomeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Mon Aug 13 16:53:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Mon Aug 13 16:53:05 CST 2018
     */
    int insert(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Mon Aug 13 16:53:05 CST 2018
     */
    int insertSelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Mon Aug 13 16:53:05 CST 2018
     */
    IncomeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Mon Aug 13 16:53:05 CST 2018
     */
    int updateByPrimaryKeySelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Mon Aug 13 16:53:05 CST 2018
     */
    int updateByPrimaryKey(IncomeRecord record);

    List<IncomeRecord> selectIncomeRecordByPage(Map<String, Object> paramMap);

    Long selectTotal(Map<String, Object> paramMap);

    /**
     * 获取状态为0，且收益时间与当前时间相同的收益记录
     * @param i
     * @return
     */
    List<IncomeRecord> selectIncomeRecordByIncomeStatusAndIncomeDate(int i);
}